title: Carobs9's GitHub Page
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A website to showcase my projects and profile.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://carobs9.github.io" # the base hostname & protocol for your site
theme: jekyll-theme-minimal # You can change this to any Jekyll theme you prefer
